import type { PlaybookData } from '@/components/playbook/playbook-page-template'

export const playbooks: PlaybookData[] = [
  {
    slug: 'founder-bottleneck',
    title: 'Fixing the Founder Bottleneck',
    subheadline: 'A diagnostic framework for founder-led businesses where too many decisions, approvals, escalations, and workflows still depend on the founder.',
    bestFor: 'Founder-led businesses where growth creates more founder pressure instead of more leverage.',
    relatedService: { name: 'Advisory & Strategy', href: '/advisory-strategy' },
    primarySymptom: 'The business slows down when the founder is unavailable.',
    whoFor: [
      'Founders involved in too many recurring decisions',
      'Teams that wait for approval before moving',
      'Businesses where knowledge is trapped in the founder\'s head',
      'Teams without clear ownership',
      'Companies growing but not gaining leverage',
      'Operators trying to reduce founder dependency',
    ],
    symptoms: [
      'The team waits for the founder before moving forward',
      'Important decisions are stuck in the founder\'s head',
      'Growth creates more pressure instead of more leverage',
      'The founder is involved in too many small decisions',
      'Work slows down when the founder is unavailable',
      'Escalations go to the founder by default',
      'Hiring has not reduced founder load',
    ],
    whatToInspect: [
      'Which decisions only the founder can make',
      'Which workflows pause without founder approval',
      'Which team members lack ownership',
      'Which processes are undocumented',
      'Which approvals repeat every week',
      'Which customer or sales situations escalate unnecessarily',
      'Which information exists only in founder memory',
    ],
    whatToFixFirst: 'Identify the top 3 recurring decisions or workflows that consume founder time every week. Convert those into documented rules, ownership, review cadence, and escalation boundaries.',
    decisionFramework: [
      'If the team lacks skill, train or hire.',
      'If the team lacks authority, define ownership.',
      'If the team lacks clarity, document the decision rules.',
      'If every exception reaches the founder, define escalation thresholds.',
      'If the founder is needed for visibility, build a dashboard or operating rhythm.',
    ],
    whatToBuild: [
      'Decision rules',
      'Role ownership map',
      'Weekly operating rhythm',
      'Approval workflows',
      'Dashboards for visibility',
      'SOPs for repeated work',
      'Escalation rules',
      'Founder exception log',
    ],
    whatToMeasure: [
      'Number of decisions removed from founder',
      'Approval time',
      'Tasks completed without founder involvement',
      'Repeated founder follow-ups',
      'Number of escalations',
      'Team ownership clarity',
      'Founder time recovered',
    ],
    commonMistakes: [
      'Hiring more people before defining ownership',
      'Automating a broken process',
      'Expecting the team to "figure it out"',
      'Keeping every important decision dependent on founder judgment',
      'Delegating tasks without decision rights',
      'Measuring output but not founder dependency',
    ],
    whenNotRightMove: 'If the business has no clear strategy, customer segment, or offer direction, start with strategic advisory first. A founder bottleneck cannot be fixed only through delegation if the real issue is unclear business direction.',
    howPressenseHelps: [
      { name: 'Advisory & Strategy', href: '/advisory-strategy' },
      { name: 'Custom Internal Tools', href: '/custom-software-internal-tools' },
      { name: 'CRM & ERP Systems', href: '/crm-erp-systems' },
      { name: 'How We Work', href: '/how-it-works' },
      { name: 'Start Diagnostic', href: '/contact' },
    ],
    faqs: [
      { question: 'What is a founder bottleneck?', answer: 'A founder bottleneck happens when too many decisions, approvals, relationships, or workflows depend on the founder. The business may be growing, but execution slows because the team cannot move without founder input.' },
      { question: 'Is founder bottleneck a hiring problem?', answer: 'Not always. Hiring can help, but only if ownership, decision rules, processes, and visibility are clear. Many founder bottlenecks continue after hiring because the business never defined what the team can own.' },
      { question: 'What should founders delegate first?', answer: 'Start with recurring decisions and workflows that happen every week. These are easier to document, assign, review, and measure than high-judgment strategic decisions.' },
      { question: 'Can systems reduce founder dependency?', answer: 'Yes. Dashboards, approval workflows, SOPs, CRM visibility, and operating rhythms can reduce dependency by making work visible and decisions repeatable.' },
      { question: 'When should a founder stay involved?', answer: 'The founder should stay involved in high-judgment decisions, strategic trade-offs, key relationships, and moments where context matters. The goal is not total removal. The goal is better leverage.' },
    ],
    relatedPlaybooks: [
      { title: 'Systems Audit & Debt Clearance', slug: 'systems-audit' },
      { title: 'GTM Clarity Reset', slug: 'gtm-clarity-reset' },
      { title: 'Revenue Leakage Diagnostic', slug: 'revenue-leakage-diagnostic' },
    ],
  },
  {
    slug: 'pricing-leakage',
    title: 'Pricing Leakage & Revenue Clarity',
    subheadline: 'A diagnostic framework for businesses that are selling, but may be losing margin through unclear pricing, discounting, weak packaging, or poor value communication.',
    bestFor: 'Businesses where revenue is active but profit, pricing confidence, or margin clarity is weak.',
    relatedService: { name: 'Advisory & Strategy', href: '/advisory-strategy' },
    primarySymptom: 'Revenue is growing, but profit does not improve proportionally.',
    whoFor: [
      'Businesses with inconsistent pricing',
      'Founders who discount too often',
      'Teams selling too many custom packages',
      'Service businesses with unclear margins',
      'Companies unsure how to communicate value',
      'Teams getting customers but struggling with profit clarity',
    ],
    symptoms: [
      'Revenue is growing but profit is not',
      'Pricing changes from client to client',
      'Sales depends on discounts',
      'Customers do not clearly understand the value',
      'The business is busy but margins feel weak',
      'Higher-effort clients pay the same as lower-effort clients',
      'Proposals feel custom every time',
    ],
    whatToInspect: [
      'Current pricing model',
      'Offer structure',
      'Discount patterns',
      'Sales objections',
      'Customer segments',
      'Delivery effort per customer',
      'Margin leakage points',
      'Proposal language',
    ],
    whatToFixFirst: 'Clarify what the business actually sells, who it is most valuable for, and where pricing does not match effort, value, risk, or complexity.',
    decisionFramework: [
      'If customers do not understand value, fix the offer narrative.',
      'If discounts are frequent, define discount boundaries.',
      'If delivery effort varies widely, redesign packages.',
      'If margins are unclear, build margin visibility.',
      'If all deals are custom, simplify the offer structure.',
    ],
    whatToBuild: [
      'Clear offer structure',
      'Pricing tiers or packages',
      'Qualification rules',
      'Discount boundaries',
      'Sales narrative',
      'Margin visibility dashboard',
      'Proposal templates',
      'Value communication framework',
    ],
    whatToMeasure: [
      'Average deal value',
      'Discount frequency',
      'Gross margin',
      'Sales cycle quality',
      'Customer fit',
      'Delivery effort versus revenue',
      'Proposal acceptance rate',
    ],
    commonMistakes: [
      'Lowering price to fix weak positioning',
      'Creating too many custom packages',
      'Selling to the wrong segment',
      'Not linking pricing to delivery effort',
      'Confusing activity with profitability',
      'Letting sales override margin logic',
    ],
    whenNotRightMove: 'If the offer itself is unclear or the business does not know its ideal customer, pricing changes alone will not fix the problem. Start with positioning, customer clarity, and offer structure first.',
    howPressenseHelps: [
      { name: 'Advisory & Strategy', href: '/advisory-strategy' },
      { name: 'Websites & Conversion', href: '/websites-conversion-systems' },
      { name: 'Content & Authority', href: '/content-authority-systems' },
      { name: 'Start Diagnostic', href: '/contact' },
    ],
    faqs: [
      { question: 'What is pricing leakage?', answer: 'Pricing leakage happens when the business loses value through underpricing, excessive discounts, unclear packages, poor qualification, or delivery effort that is not reflected in the price.' },
      { question: 'Is pricing leakage only a finance issue?', answer: 'No. It is often a strategy, positioning, sales, and delivery issue. Pricing should reflect value, complexity, customer fit, and operational effort.' },
      { question: 'Should we increase prices immediately?', answer: 'Not always. First understand where leakage is happening. The fix may be better packaging, clearer qualification, stronger value communication, or tighter discount rules.' },
      { question: 'Why do businesses discount too much?', answer: 'Discounting often happens when positioning is weak, value is unclear, sales lacks confidence, or the buyer does not understand why the offer is different.' },
      { question: 'What should we measure first?', answer: 'Start with average deal value, discount frequency, gross margin, delivery effort, and customer fit. These show whether pricing reflects the true cost and value of delivery.' },
    ],
    relatedPlaybooks: [
      { title: 'Revenue Leakage Diagnostic', slug: 'revenue-leakage-diagnostic' },
      { title: 'GTM Clarity Reset', slug: 'gtm-clarity-reset' },
      { title: 'Sales-Marketing Connection', slug: 'sales-marketing-connection' },
    ],
  },
  {
    slug: 'sales-marketing-connection',
    title: 'Building a Sales-Marketing Connection',
    subheadline: 'A diagnostic framework for companies where marketing creates activity, but sales does not consistently convert it into pipeline, revenue, or learning.',
    bestFor: 'Teams where marketing and sales are active but misaligned.',
    relatedService: { name: 'CRM & ERP Systems', href: '/crm-erp-systems' },
    primarySymptom: 'Marketing creates leads or content, but sales conversion and feedback are unclear.',
    whoFor: [
      'Teams with unclear lead quality',
      'Businesses where sales and marketing use different language',
      'Companies creating content that sales does not use',
      'Founders unsure why leads are not converting',
      'Teams with weak follow-up processes',
      'Businesses with no sales feedback loop',
    ],
    symptoms: [
      'Marketing and sales explain the offer differently',
      'Leads come in but quality is unclear',
      'Sales does not use marketing assets',
      'Marketing does not know why leads are lost',
      'Follow-up depends on individuals',
      'CRM stages do not reflect buyer reality',
      'Objections are not turned into content',
    ],
    whatToInspect: [
      'Lead sources',
      'Lead quality',
      'Sales objections',
      'Follow-up process',
      'Messaging consistency',
      'Handoff between marketing and sales',
      'Content gaps in the sales process',
      'CRM stages and definitions',
    ],
    whatToFixFirst: 'Map the buyer journey from first touch to closed deal. Identify where the buyer becomes confused, where follow-up breaks, and where sales needs better assets.',
    decisionFramework: [
      'If lead quality is unclear, define qualification criteria.',
      'If follow-up is inconsistent, build follow-up workflows.',
      'If sales ignores content, create enablement assets from real objections.',
      'If marketing lacks feedback, create a sales feedback loop.',
      'If pipeline visibility is weak, fix CRM stages.',
    ],
    whatToBuild: [
      'Shared messaging framework',
      'Lead qualification criteria',
      'Sales enablement content',
      'Follow-up sequences',
      'CRM stages',
      'Objection-handling assets',
      'Feedback loop between sales and marketing',
      'Lead source reporting',
    ],
    whatToMeasure: [
      'Lead quality',
      'Follow-up speed',
      'Conversion by source',
      'Sales objections',
      'Stage drop-offs',
      'Content usage by sales',
      'Qualified opportunity rate',
    ],
    commonMistakes: [
      'Treating marketing and sales as separate problems',
      'Generating more leads before fixing follow-up',
      'Creating content without sales input',
      'Measuring traffic instead of qualified opportunities',
      'Letting CRM stages stay vague',
      'Ignoring lost-deal reasons',
    ],
    whenNotRightMove: 'If the offer or buyer segment is unclear, sales-marketing alignment alone will not fix conversion. Start with positioning and GTM clarity first.',
    howPressenseHelps: [
      { name: 'CRM & ERP Systems', href: '/crm-erp-systems' },
      { name: 'Content & Authority', href: '/content-authority-systems' },
      { name: 'Websites & Conversion', href: '/websites-conversion-systems' },
      { name: 'Advisory & Strategy', href: '/advisory-strategy' },
      { name: 'Start Diagnostic', href: '/contact' },
    ],
    faqs: [
      { question: 'Why do sales and marketing get disconnected?', answer: 'They often work from different definitions of the buyer, offer, problem, and success. Without shared language and feedback, marketing creates activity while sales handles objections separately.' },
      { question: 'What is a good sales-marketing handoff?', answer: 'A good handoff defines lead quality, source, context, buyer pain, follow-up timing, ownership, and next action. It should be visible inside the CRM or workflow system.' },
      { question: 'Should we create more leads first?', answer: 'Not if follow-up, qualification, or conversion is weak. More leads can create more waste when the sales process is unclear.' },
      { question: 'How can content support sales?', answer: 'Content can answer objections, explain use cases, educate buyers, clarify value, and support decision-making before and after sales conversations.' },
      { question: 'What should marketing learn from sales?', answer: 'Marketing should learn which objections repeat, which buyers convert, which messages work, which leads are poor fit, and where buyers lose confidence.' },
    ],
    relatedPlaybooks: [
      { title: 'CRM Adoption & Pipeline Visibility', slug: 'crm-adoption-pipeline-visibility' },
      { title: 'GTM Clarity Reset', slug: 'gtm-clarity-reset' },
      { title: 'Website Clarity & Conversion', slug: 'website-clarity-conversion' },
    ],
  },
  {
    slug: 'customer-onboarding',
    title: 'Customer Onboarding That Sticks',
    subheadline: 'A diagnostic framework for businesses that win customers but struggle with activation, handover, education, retention, or early success.',
    bestFor: 'Businesses where customers buy but do not reach value quickly or consistently.',
    relatedService: { name: 'Custom Internal Tools', href: '/custom-software-internal-tools' },
    primarySymptom: 'Customer success depends too much on manual guidance.',
    whoFor: [
      'Businesses with inconsistent onboarding',
      'SaaS or service teams with unclear activation',
      'Companies with repeated support questions',
      'Teams with weak handover from sales to delivery',
      'Businesses seeing early churn or dissatisfaction',
      'Teams that need repeatable customer success systems',
    ],
    symptoms: [
      'Customers need too much manual guidance',
      'Onboarding varies by team member',
      'Customers do not fully use what they bought',
      'Support questions repeat',
      'Early churn or dissatisfaction appears after purchase',
      'Handover from sales to delivery is weak',
      'Success milestones are unclear',
    ],
    whatToInspect: [
      'First 30 days after purchase',
      'Customer expectations',
      'Sales-to-delivery handover',
      'Training or education gaps',
      'Success milestones',
      'Repeated support issues',
      'Ownership of onboarding',
      'Customer communication rhythm',
    ],
    whatToFixFirst: 'Define the first successful outcome the customer must reach. Then design onboarding around helping them reach that outcome quickly and clearly.',
    decisionFramework: [
      'If customers are confused, clarify first steps.',
      'If handover breaks, define sales-to-delivery transfer.',
      'If support repeats, create education assets.',
      'If onboarding varies, build checklists and milestones.',
      'If activation is low, measure time to first value.',
    ],
    whatToBuild: [
      'Onboarding checklist',
      'Welcome sequence',
      'Customer education assets',
      'Milestone tracking',
      'Internal handover process',
      'Support knowledge base',
      'Success dashboard',
      'Customer communication templates',
    ],
    whatToMeasure: [
      'Time to first value',
      'Onboarding completion rate',
      'Repeated support issues',
      'Customer engagement',
      'Early retention',
      'Customer satisfaction signals',
      'Handover completion',
    ],
    commonMistakes: [
      'Assuming the customer knows what to do next',
      'Overloading the customer with too much information',
      'Leaving onboarding to individual team members',
      'Not defining first value clearly',
      'Treating onboarding as support instead of success',
      'Ignoring what sales promised',
    ],
    whenNotRightMove: 'If the product or service does not clearly deliver value, onboarding will not fix the core issue. Start with product, offer, or customer-fit clarity first.',
    howPressenseHelps: [
      { name: 'Custom Internal Tools', href: '/custom-software-internal-tools' },
      { name: 'CRM & ERP Systems', href: '/crm-erp-systems' },
      { name: 'AI Workflows', href: '/ai-workflows-automation' },
      { name: 'Content & Authority', href: '/content-authority-systems' },
      { name: 'Start Diagnostic', href: '/contact' },
    ],
    faqs: [
      { question: 'What is customer onboarding?', answer: 'Customer onboarding is the process that helps a new customer understand, adopt, and get value from what they purchased. Good onboarding creates clarity, confidence, and early success.' },
      { question: 'Why does onboarding fail?', answer: 'It usually fails because expectations are unclear, handover is weak, success milestones are undefined, education is missing, or the process depends too much on individual team members.' },
      { question: 'What is time to first value?', answer: 'Time to first value measures how long it takes for a customer to experience the first meaningful benefit from the product or service.' },
      { question: 'Should onboarding be automated?', answer: 'Some parts can be automated, but not everything. Automation works best for repeated communication, checklists, reminders, education, and status updates. Judgment-heavy moments still need human ownership.' },
      { question: 'What should we fix first?', answer: 'Start by defining the first successful customer outcome. Then build the checklist, communication, handover, and tracking around that outcome.' },
    ],
    relatedPlaybooks: [
      { title: 'Systems Audit & Debt Clearance', slug: 'systems-audit' },
      { title: 'AI Workflow Readiness', slug: 'ai-workflow-readiness' },
      { title: 'CRM Adoption & Pipeline Visibility', slug: 'crm-adoption-pipeline-visibility' },
    ],
  },
  {
    slug: 'visibility-personal-brand',
    title: 'Visibility & Personal Brand Systems',
    subheadline: 'A diagnostic framework for founders, experts, consultants, doctors, and professionals whose expertise is strong but not visible, structured, or trusted enough in the market.',
    bestFor: 'Experts and founder-led businesses that depend on trust, authority, and clear communication.',
    relatedService: { name: 'Content & Authority Systems', href: '/content-authority-systems' },
    primarySymptom: 'The expert explains well in conversation, but the market does not consistently see that expertise.',
    whoFor: [
      'Founders building authority',
      'Doctors, specialists, consultants, and professionals',
      'Experts with inconsistent content',
      'Businesses dependent on referrals',
      'Teams with weak website trust',
      'People who want visibility without random posting',
    ],
    symptoms: [
      'Expertise is strong but not visible enough',
      'Content is inconsistent',
      'The website does not build trust',
      'The founder or expert has no repeatable content process',
      'Growth depends mostly on referrals or manual networking',
      'Content does not connect to business outcomes',
      'The market does not know what the expert should be known for',
    ],
    whatToInspect: [
      'Positioning',
      'Audience clarity',
      'Trust signals',
      'Content themes',
      'Website clarity',
      'Distribution channels',
      'Time available for content',
      'Proof and credibility assets',
    ],
    whatToFixFirst: 'Clarify what the expert should be known for and who needs to trust them. Then build a repeatable system to turn expertise into visible market assets.',
    decisionFramework: [
      'If positioning is unclear, define the authority theme.',
      'If content is inconsistent, build a workflow.',
      'If the website lacks trust, fix the authority layer.',
      'If referrals are weak, improve visibility and proof.',
      'If time is limited, use AI-assisted workflows carefully.',
    ],
    whatToBuild: [
      'Positioning narrative',
      'Website copy',
      'Authority content pillars',
      'LinkedIn or content workflow',
      'AI-assisted content system',
      'Lead magnet or diagnostic asset',
      'PR and credibility layer',
      'Case-based thought leadership',
    ],
    whatToMeasure: [
      'Content consistency',
      'Qualified inbound conversations',
      'Profile or website visits',
      'Lead quality',
      'Referral conversion',
      'Authority signals',
      'Content-to-conversation rate',
    ],
    commonMistakes: [
      'Posting random content without positioning',
      'Copying generic personal-brand advice',
      'Creating content that does not connect to business outcomes',
      'Depending fully on the expert\'s manual time',
      'Mistaking visibility for authority',
      'Publishing without a clear buyer',
    ],
    whenNotRightMove: 'If the offer, audience, or positioning is unclear, posting more content will not fix the problem. Start by clarifying the expert\'s market position and buyer relevance.',
    howPressenseHelps: [
      { name: 'Content & Authority', href: '/content-authority-systems' },
      { name: 'Websites & Conversion', href: '/websites-conversion-systems' },
      { name: 'AI Workflows', href: '/ai-workflows-automation' },
      { name: 'Advisory & Strategy', href: '/advisory-strategy' },
      { name: 'Start Diagnostic', href: '/contact' },
    ],
    faqs: [
      { question: 'What is a visibility system?', answer: 'A visibility system is a repeatable way to turn expertise into market-facing content, website clarity, trust signals, and authority assets.' },
      { question: 'Is personal branding only for LinkedIn?', answer: 'No. Personal brand includes positioning, website presence, content, search visibility, trust signals, speaking, referrals, and how the market understands the expert.' },
      { question: 'Why does expert content fail?', answer: 'It often fails because it is random, too generic, disconnected from buyer problems, or dependent on the expert\'s mood and availability.' },
      { question: 'Can AI help with personal brand content?', answer: 'Yes, but only as part of a system. AI can help with drafting, repurposing, and structure, but the point of view must come from real expertise.' },
      { question: 'What should an expert be known for?', answer: 'The answer should come from the intersection of expertise, buyer pain, credibility, market need, and commercial relevance.' },
    ],
    relatedPlaybooks: [
      { title: 'Website Clarity & Conversion', slug: 'website-clarity-conversion' },
      { title: 'GTM Clarity Reset', slug: 'gtm-clarity-reset' },
      { title: 'AI Workflow Readiness', slug: 'ai-workflow-readiness' },
    ],
  },
  {
    slug: 'systems-audit',
    title: 'Systems Audit & Debt Clearance',
    subheadline: 'A diagnostic framework for businesses slowed by spreadsheets, WhatsApp, email, disconnected SaaS tools, manual reporting, and workflows that no longer scale.',
    bestFor: 'Operations-heavy businesses that need visibility, ownership, and cleaner workflows.',
    relatedService: { name: 'Custom Internal Tools', href: '/custom-software-internal-tools' },
    primarySymptom: 'The business is growing, but execution feels slower, messier, and harder to see.',
    whoFor: [
      'Teams using too many spreadsheets',
      'Businesses relying on WhatsApp, email, and manual updates',
      'Founders without operational visibility',
      'Teams with disconnected SaaS tools',
      'Companies with repeated manual reporting',
      'Businesses where old workflows are now slowing growth',
    ],
    symptoms: [
      'Too many spreadsheets',
      'Repeated manual work',
      'Reporting is slow or unreliable',
      'Teams use different tools without one source of truth',
      'Errors increase as the business grows',
      'Founders lack visibility into operations',
      'Work gets lost between teams',
    ],
    whatToInspect: [
      'Core workflows',
      'Manual handoffs',
      'Data duplication',
      'Reporting delays',
      'Approval bottlenecks',
      'Tool overlap',
      'Processes that break at scale',
      'Ownership gaps',
    ],
    whatToFixFirst: 'Identify the highest-friction workflow that repeats every week and affects revenue, delivery, reporting, or customer experience. Fix one critical workflow before rebuilding everything.',
    decisionFramework: [
      'If the process is unclear, map it first.',
      'If reporting is slow, build visibility.',
      'If work gets lost, define ownership and handoffs.',
      'If tools overlap, simplify the stack.',
      'If one workflow hurts revenue, fix that first.',
    ],
    whatToBuild: [
      'Workflow map',
      'Internal dashboard',
      'CRM or ERP-lite system',
      'Custom internal tool',
      'Automation layer',
      'Reporting system',
      'Ownership and escalation rules',
      'Source-of-truth structure',
    ],
    whatToMeasure: [
      'Manual hours reduced',
      'Reporting speed',
      'Error rate',
      'Workflow completion time',
      'Founder or manager visibility',
      'Team adoption',
      'Handoff reliability',
    ],
    commonMistakes: [
      'Buying another tool before mapping the process',
      'Automating unclear workflows',
      'Rebuilding everything at once',
      'Ignoring team adoption',
      'Treating system debt as only a software problem',
      'Failing to assign ownership',
    ],
    whenNotRightMove: 'If the business strategy is unclear, a systems audit may expose problems but not resolve the direction. Start with advisory if the business does not know what it is trying to scale.',
    howPressenseHelps: [
      { name: 'Custom Internal Tools', href: '/custom-software-internal-tools' },
      { name: 'CRM & ERP Systems', href: '/crm-erp-systems' },
      { name: 'AI Workflows', href: '/ai-workflows-automation' },
      { name: 'How We Work', href: '/how-it-works' },
      { name: 'Start Diagnostic', href: '/contact' },
    ],
    faqs: [
      { question: 'What is systems debt?', answer: 'Systems debt is the operational mess that builds when a business grows on top of spreadsheets, manual work, disconnected tools, unclear ownership, and undocumented processes.' },
      { question: 'How do we know if we have systems debt?', answer: 'Signs include repeated manual reporting, slow handoffs, duplicate data, unclear ownership, too many spreadsheets, and founders constantly asking for updates.' },
      { question: 'Should we replace all tools at once?', answer: 'No. Start with one high-friction workflow. Rebuilding everything at once usually creates disruption and weak adoption.' },
      { question: 'Is systems debt solved by automation?', answer: 'Not always. Automation helps only after the workflow is clear. Automating unclear processes can make errors faster.' },
      { question: 'What should we audit first?', answer: 'Start with the workflow that repeats often and affects revenue, delivery, reporting, or customer experience.' },
    ],
    relatedPlaybooks: [
      { title: 'Internal Tool Readiness', slug: 'internal-tool-readiness' },
      { title: 'CRM Adoption & Pipeline Visibility', slug: 'crm-adoption-pipeline-visibility' },
      { title: 'AI Workflow Readiness', slug: 'ai-workflow-readiness' },
    ],
  },
  {
    slug: 'website-clarity-conversion',
    title: 'Website Clarity & Conversion Audit',
    subheadline: 'A diagnostic framework for businesses whose website looks fine but does not help buyers understand, trust, qualify, or take action.',
    bestFor: 'Businesses with weak website conversion, unclear messaging, or poor-fit inbound leads.',
    relatedService: { name: 'Websites & Conversion Systems', href: '/websites-conversion-systems' },
    primarySymptom: 'People visit the website, but they do not clearly understand or act.',
    whoFor: [
      'Businesses with traffic but low inquiries',
      'Companies whose sales calls explain the offer better than the website',
      'Founders who feel the website no longer reflects the business',
      'SaaS, service, consulting, or expert-led businesses with complex offers',
      'Teams entering a new market',
      'Businesses investing in content, outbound, or referrals',
    ],
    symptoms: [
      'Visitors do not understand the business quickly',
      'The site sounds generic',
      'The offer is not clearly explained',
      'CTAs are weak or vague',
      'Proof is missing or scattered',
      'Pages do not guide buyers toward a decision',
      'Traffic does not convert into qualified conversations',
    ],
    whatToInspect: [
      'Homepage clarity',
      'First-screen messaging',
      'Service or solution pages',
      'Buyer journey',
      'Proof and credibility',
      'CTAs',
      'Navigation',
      'Qualification signals',
      'FAQ quality',
      'Content pathways',
    ],
    whatToFixFirst: 'Clarify the buyer\'s problem, who the offer is for, why it matters, and what action the right-fit buyer should take next.',
    decisionFramework: [
      'If visitors do not understand the offer, fix messaging first.',
      'If traffic is weak, review SEO and content pathways.',
      'If inquiries are poor fit, add qualification.',
      'If sales calls explain better than the site, rebuild the narrative.',
      'If proof is weak, add credibility and examples.',
    ],
    whatToBuild: [
      'Positioning-led homepage',
      'Service or solution pages',
      'Buyer journey structure',
      'Proof sections',
      'FAQ sections',
      'Qualification copy',
      'Landing pages',
      'SEO and AEO-ready content pathways',
    ],
    whatToMeasure: [
      'Qualified inquiries',
      'CTA clicks',
      'Scroll depth',
      'Form submissions',
      'Time on key pages',
      'Conversion by source',
      'Poor-fit inquiry reduction',
      'Sales-call clarity',
    ],
    commonMistakes: [
      'Redesigning before fixing positioning',
      'Making the site look better without clarifying the offer',
      'Using generic category language',
      'Hiding proof too low on the page',
      'Sending traffic to unclear pages',
      'Using vague CTAs',
    ],
    whenNotRightMove: 'If the business model, offer, or ideal buyer is unclear, a website rebuild may be premature. Start with advisory or positioning before design and development.',
    howPressenseHelps: [
      { name: 'Websites & Conversion', href: '/websites-conversion-systems' },
      { name: 'Content & Authority', href: '/content-authority-systems' },
      { name: 'Advisory & Strategy', href: '/advisory-strategy' },
      { name: 'What We Fix', href: '/about' },
      { name: 'Start Diagnostic', href: '/contact' },
    ],
    faqs: [
      { question: 'Why do good-looking websites fail?', answer: 'A website can look polished and still fail if buyers do not understand what the business does, who it helps, why it matters, and what to do next.' },
      { question: 'What is website clarity?', answer: 'Website clarity means visitors can quickly understand the problem you solve, who you serve, your value, your proof, and the next step.' },
      { question: 'Should we redesign or rewrite first?', answer: 'Usually rewrite and restructure first. Design should support the message, not hide unclear positioning.' },
      { question: 'What is a conversion system?', answer: 'A conversion system is the combination of positioning, page flow, proof, CTAs, qualification, FAQs, and content paths that help the right buyer take action.' },
      { question: 'Can this improve SEO and AEO?', answer: 'Yes. Clear pages with specific answers, structured sections, FAQs, and internal links are easier for users, search engines, and AI systems to understand.' },
    ],
    relatedPlaybooks: [
      { title: 'Visibility & Personal Brand', slug: 'visibility-personal-brand' },
      { title: 'GTM Clarity Reset', slug: 'gtm-clarity-reset' },
      { title: 'Content & Authority Systems', slug: 'visibility-personal-brand' },
    ],
  },
  {
    slug: 'crm-adoption-pipeline-visibility',
    title: 'CRM Adoption & Pipeline Visibility Fix',
    subheadline: 'A diagnostic framework for teams whose CRM exists but is not trusted, used consistently, or useful for sales and operational decisions.',
    bestFor: 'Teams with weak CRM adoption, unclear pipeline visibility, or inconsistent follow-up.',
    relatedService: { name: 'CRM & ERP Systems', href: '/crm-erp-systems' },
    primarySymptom: 'The CRM exists, but leadership still has to ask people what is happening.',
    whoFor: [
      'Sales teams using CRM inconsistently',
      'Founders without reliable pipeline visibility',
      'Businesses missing follow-ups',
      'Teams with unclear lead ownership',
      'Companies where CRM data is incomplete',
      'Businesses connecting sales, operations, and finance',
    ],
    symptoms: [
      'CRM data is incomplete or outdated',
      'Team members avoid using the CRM',
      'Pipeline stages are unclear',
      'Follow-ups depend on memory',
      'Leadership cannot trust reports',
      'Sales and operations are disconnected',
      'Leads fall through cracks',
    ],
    whatToInspect: [
      'CRM fields',
      'Pipeline stages',
      'Lead ownership',
      'Follow-up rules',
      'Reporting dashboards',
      'Data quality',
      'Sales-to-operations handoff',
      'Team adoption barriers',
    ],
    whatToFixFirst: 'Define the pipeline stages, ownership rules, required data, follow-up expectations, and reporting needs before changing tools.',
    decisionFramework: [
      'If the team avoids CRM, inspect usability and discipline.',
      'If reports are unreliable, fix data quality.',
      'If leads are missed, define ownership and follow-up rules.',
      'If stages are unclear, redesign the pipeline.',
      'If the tool does not match the process, reconfigure or build around it.',
    ],
    whatToBuild: [
      'CRM stage logic',
      'Lead ownership rules',
      'Follow-up workflows',
      'Reporting dashboard',
      'Sales handoff process',
      'Data hygiene rules',
      'Pipeline review rhythm',
      'CRM automation where useful',
    ],
    whatToMeasure: [
      'CRM usage',
      'Follow-up speed',
      'Data completeness',
      'Stage conversion',
      'Lead response time',
      'Pipeline accuracy',
      'Lost-deal reasons',
      'Revenue visibility',
    ],
    commonMistakes: [
      'Blaming the tool before defining the process',
      'Adding fields no one uses',
      'Creating reports from bad data',
      'Automating follow-ups without ownership',
      'Making CRM work only for management',
      'Ignoring team adoption',
    ],
    whenNotRightMove: 'If the sales process itself is unclear, CRM changes will not fix it. Start with sales process, qualification, and GTM clarity before implementation.',
    howPressenseHelps: [
      { name: 'CRM & ERP Systems', href: '/crm-erp-systems' },
      { name: 'Custom Internal Tools', href: '/custom-software-internal-tools' },
      { name: 'AI Workflows', href: '/ai-workflows-automation' },
      { name: 'Advisory & Strategy', href: '/advisory-strategy' },
      { name: 'Start Diagnostic', href: '/contact' },
    ],
    faqs: [
      { question: 'Why do CRMs fail?', answer: 'CRMs often fail because the process is unclear, fields are poorly designed, ownership is weak, data quality is low, or the team does not see value in using the system.' },
      { question: 'Is CRM adoption a software problem?', answer: 'Partly, but not only. Adoption depends on process clarity, leadership discipline, usability, reporting value, and team ownership.' },
      { question: 'What should a CRM show leadership?', answer: 'It should show pipeline status, ownership, follow-up risk, stage movement, lead quality, revenue visibility, and where deals are getting stuck.' },
      { question: 'Should we change CRM platforms?', answer: 'Not immediately. First diagnose whether the issue is the tool, process, data, ownership, or adoption. Changing platforms can recreate the same problem.' },
      { question: 'Can CRM connect with internal tools?', answer: 'Yes. CRM systems can connect with dashboards, approval workflows, customer onboarding, ERP-lite systems, and AI-assisted follow-up workflows.' },
    ],
    relatedPlaybooks: [
      { title: 'Sales-Marketing Connection', slug: 'sales-marketing-connection' },
      { title: 'Revenue Leakage Diagnostic', slug: 'revenue-leakage-diagnostic' },
      { title: 'Systems Audit & Debt Clearance', slug: 'systems-audit' },
    ],
  },
  {
    slug: 'ai-workflow-readiness',
    title: 'AI Workflow Readiness Playbook',
    subheadline: 'A diagnostic framework for teams experimenting with AI but struggling to turn it into repeatable, reliable, and useful execution.',
    bestFor: 'Teams using AI across content, sales, research, support, or operations without a clear workflow.',
    relatedService: { name: 'AI Workflows & Automation', href: '/ai-workflows-automation' },
    primarySymptom: 'People are using AI, but the business has not gained consistent execution leverage.',
    whoFor: [
      'Teams experimenting with AI tools',
      'Founders using AI for scattered tasks',
      'Content teams trying to speed up output',
      'Sales teams needing research or follow-up support',
      'Operations teams with repeated manual work',
      'Businesses wanting automation without chaos',
    ],
    symptoms: [
      'AI usage is inconsistent',
      'Prompts live in random chats',
      'Output quality varies widely',
      'No one owns the workflow',
      'AI work is not reviewed properly',
      'Experiments do not become systems',
      'Teams still feel slow despite using AI',
    ],
    whatToInspect: [
      'Repeated tasks',
      'Inputs and outputs',
      'Workflow owner',
      'Review standards',
      'Prompt storage',
      'Tool access',
      'Data sensitivity',
      'Handoff after AI output',
    ],
    whatToFixFirst: 'Choose one repeated workflow where inputs, outputs, ownership, review, and business value can be clearly defined.',
    decisionFramework: [
      'If the workflow is unclear, map it first.',
      'If output needs judgment, add review.',
      'If prompts are scattered, create a prompt system.',
      'If the task is variable, do not automate yet.',
      'If AI can support speed without reducing quality, pilot one workflow.',
    ],
    whatToBuild: [
      'AI workflow map',
      'Prompt library',
      'Review checklist',
      'Content or research workflow',
      'Follow-up assistance',
      'Reporting automation',
      'Internal knowledge system',
      'Governance and ownership rules',
    ],
    whatToMeasure: [
      'Time saved',
      'Output consistency',
      'Review effort',
      'Adoption',
      'Error rate',
      'Workflow completion time',
      'Manual effort reduced',
    ],
    commonMistakes: [
      'Starting with tools instead of workflows',
      'Automating tasks without review',
      'Letting prompts stay scattered',
      'Using AI where judgment is required',
      'Expecting AI to fix unclear systems',
      'Scaling experiments before proving usefulness',
    ],
    whenNotRightMove: 'If the workflow is unclear, sensitive, high-risk, or too variable, AI should not be the first move. Start with process clarity, templates, or ownership rules.',
    howPressenseHelps: [
      { name: 'AI Workflows', href: '/ai-workflows-automation' },
      { name: 'Custom Internal Tools', href: '/custom-software-internal-tools' },
      { name: 'Content & Authority', href: '/content-authority-systems' },
      { name: 'CRM & ERP Systems', href: '/crm-erp-systems' },
      { name: 'Start Diagnostic', href: '/contact' },
    ],
    faqs: [
      { question: 'What is AI workflow readiness?', answer: 'AI workflow readiness means a process has clear inputs, outputs, ownership, review standards, and enough repetition for AI to support it without creating more confusion.' },
      { question: 'Why do AI experiments fail?', answer: 'They often fail because teams start with tools, not workflows. Prompts are scattered, ownership is unclear, and outputs do not connect to the next step.' },
      { question: 'What should we automate first?', answer: 'Start with repeated, low-to-medium-risk work where the output can be reviewed and the business value is clear.' },
      { question: 'Should AI replace human review?', answer: 'No. In most business workflows, AI should support human judgment, not replace review, ownership, or accountability.' },
      { question: 'Can AI help small teams scale?', answer: 'Yes, when applied to the right workflows. It can reduce repeated work, improve consistency, and support execution, but only when the process is already clear.' },
    ],
    relatedPlaybooks: [
      { title: 'Systems Audit & Debt Clearance', slug: 'systems-audit' },
      { title: 'Content & Authority Systems', slug: 'visibility-personal-brand' },
      { title: 'CRM Adoption & Pipeline Visibility', slug: 'crm-adoption-pipeline-visibility' },
    ],
  },
  {
    slug: 'internal-tool-readiness',
    title: 'Internal Tool Readiness Playbook',
    subheadline: 'A diagnostic framework for businesses deciding whether to build custom internal software, use SaaS, automate, or simplify the process first.',
    bestFor: 'Businesses considering dashboards, portals, trackers, approval systems, CRM workflows, or operations tools.',
    relatedService: { name: 'Custom Internal Tools', href: '/custom-software-internal-tools' },
    primarySymptom: 'The team knows a workflow is painful but is unsure whether software is the right fix.',
    whoFor: [
      'Businesses outgrowing spreadsheets',
      'Teams with repeated manual workflows',
      'Founders considering custom software',
      'Companies unsure whether SaaS fits',
      'Operations-heavy teams needing visibility',
      'Businesses with broken handoffs',
    ],
    symptoms: [
      'The same workflow repeats every week',
      'Work depends on spreadsheets or manual updates',
      'Multiple people are involved',
      'Mistakes affect revenue or delivery',
      'Reporting is slow',
      'Existing SaaS does not fit',
      'The founder manually follows up too often',
    ],
    whatToInspect: [
      'Workflow frequency',
      'Business impact',
      'Users involved',
      'Data required',
      'Exceptions',
      'Current tools',
      'Reporting needs',
      'Ownership and adoption readiness',
    ],
    whatToFixFirst: 'Map the workflow before deciding what to build. Identify the users, data, handoffs, exceptions, reporting needs, and owner.',
    decisionFramework: [
      'If SaaS solves it well, use SaaS.',
      'If the process is unclear, do not build yet.',
      'If the workflow is repeated and painful, consider a custom tool.',
      'If visibility is the main issue, start with a dashboard.',
      'If adoption is unlikely, fix ownership first.',
    ],
    whatToBuild: [
      'Workflow map',
      'Prototype or pilot',
      'Dashboard',
      'Approval system',
      'Internal portal',
      'Custom CRM workflow',
      'ERP-lite layer',
      'Automation layer',
    ],
    whatToMeasure: [
      'Manual effort reduced',
      'Workflow completion time',
      'Reporting speed',
      'Error reduction',
      'Adoption',
      'Visibility',
      'Founder follow-up reduction',
    ],
    commonMistakes: [
      'Building before mapping the process',
      'Rebuilding everything at once',
      'Ignoring adoption',
      'Choosing custom software when SaaS is enough',
      'Automating exceptions too early',
      'Building without a clear owner',
    ],
    whenNotRightMove: 'Do not build an internal tool if the workflow is unclear, the team is not ready, SaaS solves the problem, or the issue is strategic rather than operational.',
    howPressenseHelps: [
      { name: 'Custom Internal Tools', href: '/custom-software-internal-tools' },
      { name: 'CRM & ERP Systems', href: '/crm-erp-systems' },
      { name: 'AI Workflows', href: '/ai-workflows-automation' },
      { name: 'How We Work', href: '/how-it-works' },
      { name: 'Start Diagnostic', href: '/contact' },
    ],
    faqs: [
      { question: 'When should a business build an internal tool?', answer: 'Build when the workflow is repeated, important, painful, involves multiple people, affects revenue or delivery, and is not handled well by current tools.' },
      { question: 'Should we use SaaS or custom software?', answer: 'Use SaaS when it fits the workflow well. Consider custom software when SaaS is too rigid, bloated, expensive, or misaligned with how the business operates.' },
      { question: 'What should we build first?', answer: 'Start with one high-friction workflow. A focused pilot is usually better than a large internal platform rebuild.' },
      { question: 'Why do internal tools fail?', answer: 'They fail when the process is unclear, adoption is ignored, ownership is missing, or the tool creates extra work instead of reducing friction.' },
      { question: 'Can internal tools connect with AI or CRM?', answer: 'Yes. Internal tools can connect with CRM systems, ERP-lite systems, dashboards, AI workflows, reporting, and automation layers.' },
    ],
    relatedPlaybooks: [
      { title: 'Systems Audit & Debt Clearance', slug: 'systems-audit' },
      { title: 'CRM Adoption & Pipeline Visibility', slug: 'crm-adoption-pipeline-visibility' },
      { title: 'AI Workflow Readiness', slug: 'ai-workflow-readiness' },
    ],
  },
  {
    slug: 'gtm-clarity-reset',
    title: 'GTM Clarity Reset',
    subheadline: 'A diagnostic framework for businesses where marketing, sales, positioning, audience, offer, and channel decisions feel active but scattered.',
    bestFor: 'Founder-led businesses entering a market, repositioning, or trying to make growth more focused.',
    relatedService: { name: 'Advisory & Strategy', href: '/advisory-strategy' },
    primarySymptom: 'The business is doing growth activity, but the direction feels unclear.',
    whoFor: [
      'Founders unsure who to target first',
      'Teams entering new markets',
      'Businesses with weak positioning',
      'Companies doing content, outbound, and ads without clarity',
      'Teams with inconsistent messaging',
      'Businesses struggling to explain their value',
    ],
    symptoms: [
      'Marketing activity feels scattered',
      'The ideal buyer is unclear',
      'Sales and content use different language',
      'Channels are chosen without a clear reason',
      'The offer is hard to explain',
      'Competitor comparison is weak',
      'The team is busy but not focused',
    ],
    whatToInspect: [
      'Target segment',
      'Buyer pain',
      'Positioning',
      'Offer structure',
      'Competitive alternatives',
      'Messaging',
      'Channel fit',
      'Sales objections',
      'Proof and credibility',
    ],
    whatToFixFirst: 'Clarify who the business is targeting, what problem it is solving, why the buyer should care now, and what message should lead.',
    decisionFramework: [
      'If the buyer is unclear, define the segment.',
      'If the offer is unclear, fix packaging.',
      'If the message is generic, sharpen positioning.',
      'If channels are scattered, prioritize based on buyer behavior.',
      'If sales objections repeat, turn them into messaging and content.',
    ],
    whatToBuild: [
      'GTM narrative',
      'ICP definition',
      'Positioning statement',
      'Offer structure',
      'Messaging framework',
      'Channel priority map',
      'Sales and content angles',
      '90-day GTM roadmap',
    ],
    whatToMeasure: [
      'Qualified conversations',
      'Conversion by channel',
      'Message resonance',
      'Sales objections',
      'Lead quality',
      'Pipeline quality',
      'Content-to-inquiry signals',
    ],
    commonMistakes: [
      'Starting campaigns before positioning',
      'Targeting too broadly',
      'Copying competitor language',
      'Treating all channels equally',
      'Creating content without buyer insight',
      'Confusing visibility with demand',
    ],
    whenNotRightMove: 'If the business has no capacity to execute, a GTM reset may create clarity but not momentum. Fix team ownership and operating rhythm alongside GTM strategy.',
    howPressenseHelps: [
      { name: 'Advisory & Strategy', href: '/advisory-strategy' },
      { name: 'Content & Authority', href: '/content-authority-systems' },
      { name: 'Websites & Conversion', href: '/websites-conversion-systems' },
      { name: 'CRM & ERP Systems', href: '/crm-erp-systems' },
      { name: 'Start Diagnostic', href: '/contact' },
    ],
    faqs: [
      { question: 'What is GTM clarity?', answer: 'GTM clarity means the business knows who it is targeting, what problem it solves, how to position the offer, what message to lead with, and which channels deserve focus.' },
      { question: 'Why does GTM become scattered?', answer: 'It often becomes scattered when the business tries many channels before clarifying buyer pain, positioning, offer structure, and sales feedback.' },
      { question: 'Should we run ads before GTM clarity?', answer: 'Usually no. Paid traffic can amplify confusion if the offer, buyer, message, or landing page is unclear.' },
      { question: 'What should a GTM reset produce?', answer: 'It should produce a clearer target segment, positioning statement, offer structure, channel priorities, messaging angles, and execution roadmap.' },
      { question: 'How does GTM connect to content and website?', answer: 'GTM gives content and website work direction. Without GTM clarity, pages and content often become generic.' },
    ],
    relatedPlaybooks: [
      { title: 'Website Clarity & Conversion', slug: 'website-clarity-conversion' },
      { title: 'Sales-Marketing Connection', slug: 'sales-marketing-connection' },
      { title: 'Pricing Leakage & Revenue Clarity', slug: 'pricing-leakage' },
    ],
  },
  {
    slug: 'revenue-leakage-diagnostic',
    title: 'Revenue Leakage Diagnostic',
    subheadline: 'A diagnostic framework for businesses where leads, follow-ups, margins, handoffs, customer opportunities, or delivery quality are being lost through unclear systems.',
    bestFor: 'Businesses that are busy but suspect revenue is slipping through operational gaps.',
    relatedService: { name: 'Advisory & Strategy', href: '/advisory-strategy' },
    primarySymptom: 'The business is generating activity, but too much value is being lost before, during, or after the sale.',
    whoFor: [
      'Businesses with missed follow-ups',
      'Teams with unclear lead ownership',
      'Companies with margin leakage',
      'Founders unsure where revenue is being lost',
      'Businesses with poor sales-to-delivery handoff',
      'Teams with inconsistent customer expansion',
    ],
    symptoms: [
      'Leads are missed or followed up late',
      'Opportunities are lost without clear reasons',
      'Discounts are too frequent',
      'Margins are unclear',
      'Delivery effort exceeds revenue',
      'Customers are not expanded or retained well',
      'Sales, delivery, and finance are disconnected',
    ],
    whatToInspect: [
      'Lead capture',
      'Follow-up speed',
      'Qualification',
      'Sales process',
      'Pricing and discounting',
      'Delivery effort',
      'Handoffs',
      'Customer retention and expansion',
      'Reporting visibility',
    ],
    whatToFixFirst: 'Map the revenue path from first inquiry to delivery and retention. Identify where value is lost, delayed, discounted, duplicated, or poorly owned.',
    decisionFramework: [
      'If leads are missed, fix capture and ownership.',
      'If follow-up is slow, build CRM workflows.',
      'If margins are weak, inspect pricing and delivery effort.',
      'If handoffs break, define ownership.',
      'If retention is weak, inspect onboarding and customer success.',
    ],
    whatToBuild: [
      'Revenue leakage map',
      'Lead ownership rules',
      'Follow-up workflows',
      'Qualification criteria',
      'Pricing boundaries',
      'Sales-to-delivery handoff',
      'Margin visibility dashboard',
      'Customer expansion process',
    ],
    whatToMeasure: [
      'Lead response time',
      'Lost opportunities',
      'Discount frequency',
      'Gross margin',
      'Delivery effort',
      'Handoff completion',
      'Retention',
      'Expansion revenue',
    ],
    commonMistakes: [
      'Trying to generate more leads before fixing leakage',
      'Ignoring follow-up speed',
      'Treating margin problems as only finance problems',
      'Letting sales and delivery operate separately',
      'Not tracking lost-deal reasons',
      'Failing to connect pricing to delivery effort',
    ],
    whenNotRightMove: 'If the business does not have enough demand yet, revenue leakage may not be the main constraint. Start with GTM clarity, positioning, website, or content before optimizing leakage.',
    howPressenseHelps: [
      { name: 'Advisory & Strategy', href: '/advisory-strategy' },
      { name: 'CRM & ERP Systems', href: '/crm-erp-systems' },
      { name: 'Custom Internal Tools', href: '/custom-software-internal-tools' },
      { name: 'Websites & Conversion', href: '/websites-conversion-systems' },
      { name: 'Start Diagnostic', href: '/contact' },
    ],
    faqs: [
      { question: 'What is revenue leakage?', answer: 'Revenue leakage is value lost through missed leads, slow follow-up, poor qualification, excessive discounting, weak handoffs, unclear margins, delivery inefficiency, or poor retention.' },
      { question: 'Is revenue leakage a sales problem?', answer: 'Sometimes, but not always. It can come from marketing, CRM, pricing, operations, delivery, finance, onboarding, or customer success.' },
      { question: 'Should we fix leakage before getting more leads?', answer: 'Often yes. More leads can create more waste if follow-up, qualification, CRM visibility, pricing, or handoffs are broken.' },
      { question: 'How do we find where revenue is leaking?', answer: 'Map the full path from lead capture to sale, delivery, retention, and expansion. Then inspect where value is lost, delayed, discounted, or poorly owned.' },
      { question: 'What systems help reduce revenue leakage?', answer: 'CRM workflows, lead ownership rules, dashboards, pricing boundaries, handoff processes, onboarding systems, and internal tools can all help reduce leakage.' },
    ],
    relatedPlaybooks: [
      { title: 'Pricing Leakage & Revenue Clarity', slug: 'pricing-leakage' },
      { title: 'CRM Adoption & Pipeline Visibility', slug: 'crm-adoption-pipeline-visibility' },
      { title: 'Customer Onboarding That Sticks', slug: 'customer-onboarding' },
    ],
  },
]

export function getPlaybookBySlug(slug: string): PlaybookData | undefined {
  return playbooks.find((p) => p.slug === slug)
}

export function getAllPlaybookSlugs(): string[] {
  return playbooks.map((p) => p.slug)
}
